POST http://localhost:5000/api/v1/users/
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@admin.com",
    "password": "admin",
    "confirmPassword": "admin",
    "gender": "male",
    "role": "admin"
}

###
POST http://localhost:5000/api/v1/login/
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}